/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Modal: typeof import('./src/components/modal/index.vue')['default']
    ModalBody: typeof import('./src/components/modal/body.vue')['default']
    ModalFooter: typeof import('./src/components/modal/footer.vue')['default']
    ModalTest: typeof import('./src/components/modal/test.vue')['default']
    Notification: typeof import('./src/components/notification.vue')['default']
    Snackbar: typeof import('./src/components/snackbar.vue')['default']
    TagBody: typeof import('./src/components/tagBody.vue')['default']
    Toast: typeof import('./src/components/toast.vue')['default']
  }
}
