/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconPhConfetti: typeof import('~icons/ph/confetti')['default']
    IconPhX: typeof import('~icons/ph/x')['default']
    Modal: typeof import('./src/components/modal.vue')['default']
    ModalBody: typeof import('./src/components/modal/body.vue')['default']
    ModalFooter: typeof import('./src/components/modal/footer.vue')['default']
    ModalSlotsBody: typeof import('./src/components/modal-slots/body.vue')['default']
    ModalSlotsDefault: typeof import('./src/components/modal-slots/default.vue')['default']
    ModalSlotsHeader: typeof import('./src/components/modal-slots/header.vue')['default']
    ModalTest: typeof import('./src/components/modal/test.vue')['default']
    Notification: typeof import('./src/components/notification.vue')['default']
    Snackbar: typeof import('./src/components/snackbar.vue')['default']
    TagBody: typeof import('./src/components/tagBody.vue')['default']
    Toast: typeof import('./src/components/toast.vue')['default']
  }
}
